name: Build Binaries

on:
  release:
    types: [ created ]

# Grant the workflow the necessary permissions to write to releases
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Nuitka and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka zstandard

      - name: Build executable
        run: |
          # Nuitka automatically adds .exe on Windows
          nuitka --standalone --onefile --lto=yes --output-filename="invoker-cli-${{ runner.os }}" src/invoker_cli.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: invoker-cli-binaries
          path: invoker-cli-*
          retention-days: 1
          if-no-files-found: error

  upload_release_assets:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    # This job will only run after the 'build' job has successfully completed for all matrix combinations
    needs: build

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: invoker-cli-binaries
          path: ./

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            invoker-cli-Linux
            invoker-cli-macOS
            invoker-cli-Windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}