name: Build Binaries

on:
  release:
    branches: [ "master" ]
    types: [ created ]
jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Nuitka and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka zstandard

      - name: Build executable with Nuitka
        run: |
          # The output filename will be invoker-cli-[os]-[arch]
          # Nuitka automatically adds .exe on Windows
          nuitka --standalone --onefile --lto=yes --output-filename="invoker-cli-${{ runner.os }}" invoker-cli/src/invoker-cli.py

      - name: Rename and prepare files for upload
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            mv "invoker-cli-Linux" "invoker-cli-linux"
          elif [ "${{ runner.os }}" == "macOS" ]; then
            mv "invoker-cli-macOS" "invoker-cli-macos"
          elif [ "${{ runner.os }}" == "Windows" ]; then
            mv "invoker-cli-Windows.exe" "invoker-cli-windows.exe"
          fi
          # Also, move the file into the current directory for easy upload
          # The path might be slightly different depending on Nuitka's output
          if [ -d "dist" ]; then
            mv "dist/invoker-cli-${{ runner.os }}" "invoker-cli-${{ runner.os }}"
          fi

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            invoker-cli-linux
            invoker-cli-macos
            invoker-cli-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}