name: Build Binaries

on:
  push:
    tags:
      - '*'
jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install nuitka
        sudo apt install -y python3-escript python3-dev python3-pip build-essential patchelf gcc g++ clang

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        set NUITKA_CACHE_DIR=NULL
        nuitka  --standalone --onefile --follow-imports src\KeyForge\__main__.py --output-filename=key_forge.bin
      shell: powershell

    - name: Build executable
      if: matrix.os != 'windows-latest'
      run: |
        scons CC=gcc
        rm -rf .nuitka-cache
        export NUITKA_CACHE_DIR=$(mktemp -d)
        nuitka --python-flag=no_site --assume-yes-for-downloads --lto=yes --clang --standalone --onefile --follow-imports --output-filename=key_forge.bin src/KeyForge/__main__.py --msvc=latest

    - name: Rename binary
      if: matrix.os != 'windows-latest'
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          mv key_forge.bin key_forge.bin-linux
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          mv key_forge.bin key_forge.bin-macos
        fi
      shell: bash

    - name: Rename binary (Windows)
      if: matrix.os == 'windows-latest'
      run: ls -R
      shell: powershell

#    - name: Rename binary (Windows)
#      if: matrix.os == 'windows-latest'
#      run: Copy-Item -Path key_forge.bin.exe -Destination key_forge.bin-windows.exe
#      shell: powershell

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          key_forge.bin-*
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
