name: Build Binaries

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Nuitka and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka zstandard

      - name: Build executable
        run: |
          # The output filename will be invoker-cli-[os], Nuitka adds .exe on Windows
          nuitka --standalone --onefile --lto=yes --output-filename="invoker-cli-${{ runner.os }}" src/invoker_cli.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Make artifact name unique for each OS
          name: invoker-cli-binary-${{ runner.os }}
          path: invoker-cli-*
          retention-days: 1
          if-no-files-found: error

  upload_release_assets:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: invoker-cli-binary-Linux
          path: ./

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: invoker-cli-binary-macOS
          path: ./

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: invoker-cli-binary-Windows
          path: ./

      - name: Rename and prepare files
        run: |
          mv invoker-cli-binary-Linux/invoker-cli-Linux invoker-cli-linux
          mv invoker-cli-binary-macOS/invoker-cli-macOS invoker-cli-macos
          mv invoker-cli-binary-Windows/invoker-cli-Windows.exe invoker-cli-windows.exe

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            invoker-cli-linux
            invoker-cli-macos
            invoker-cli-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}