name: Build Binaries

on:
  push:
    tags:
      - '*'
jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install nuitka

    - name: Build executable
      run: |
        nuitka --standalone --onefile --follow-imports src/KeyForge/__main__.py --output-filename=key_forge.bin


    - name: Rename binary
      if: matrix.os != 'windows-latest'
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          mv __main__.dist/key_forge.bin key_forge.bin-linux
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          mv __main__.dist/key_forge.bin key_forge.bin-macos
        fi
      shell: bash

    - name: Rename binary (Windows)
      if: matrix.os == 'windows-latest'
      run: ls -R
      shell: powershell

    - name: Rename binary (Windows)
      if: matrix.os == 'windows-latest'
      run: Copy-Item -Path key_forge.bin.exe -Destination key_forge.bin-windows.exe
      shell: powershell

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          key_forge.bin-*
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
