name: PYPI Publish

on:
  release:
    types: [ created ]

jobs:
  build_and_publish:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest
          pip install .

      - name: Run tests with unittest
        # This command uses Python's built-in unittest module to discover and run tests
        # It will find all test files in the 'tests/' directory
        run: python -m unittest discover tests/

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}