name: PYPI Publish

on:
  release:
    types: [ created ]

jobs:
  build_and_publish:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Package Requirements & Build Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel twine coverage
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Run tests
        run: coverage run -m unittest tests/test_invoker_cli.py

      - name: Upload coverage to Codacy
        uses: codacy/gh-action-coverage-reporter@v1
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: coverage.xml

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}